server:
  port: 8084
spring:
  application:
    name: MyLoginService
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mythrid?serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
  cloud:
    nacos:
      server-addr: 127.0.0.1
      discovery:
        server-addr: 127.0.0.1
        namespace: public